backend:
  name: github
  repo: mmisk-coder/linnmar-poms
  branch: main
  client_id: Ov23lioX8sOnP35i8MGH

media_folder: "images"
public_folder: "/images"

collections:

  - name: "members"
    label: "Members"
    folder: "content/members"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "role", widget: "string" }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Grade", name: "grade", widget: "string", required: false }
      - { label: "Bio", name: "bio", widget: "text", required: false }

  - name: "coaches"
    label: "Coaches"
    folder: "content/coaches"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Team", name: "team", widget: "select", options: ["Varsity", "JV"] }
      - { label: "Title", name: "role", widget: "string" }
      - { label: "Photo", name: "image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }

  - name: "photos"
    label: "Photos"
    folder: "content/photos"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
